@echo off
py .\slides20.py -b pftl -s 009 -lang esp --ppt -output spanish/pftl-009-esp.pptx
py .\slides20.py -b pftl -s 012 -lang esp --ppt -output spanish/pftl-012-esp.pptx
py .\slides20.py -b pftl -s 017 -lang esp --ppt -output spanish/pftl-017-esp.pptx
py .\slides20.py -b pftl -s 019 -lang esp --ppt -output spanish/pftl-019-esp.pptx
py .\slides20.py -b pftl -s 022 -lang esp --ppt -output spanish/pftl-022-esp.pptx
py .\slides20.py -b pftl -s 025 -lang esp --ppt -output spanish/pftl-025-esp.pptx
py .\slides20.py -b pftl -s 029 -lang esp --ppt -output spanish/pftl-029-esp.pptx
py .\slides20.py -b pftl -s 037 -lang esp --ppt -output spanish/pftl-037-esp.pptx
py .\slides20.py -b pftl -s 048 -lang esp --ppt -output spanish/pftl-048-esp.pptx
py .\slides20.py -b pftl -s 050 -lang esp --ppt -output spanish/pftl-050-esp.pptx
py .\slides20.py -b pftl -s 053 -lang esp --ppt -output spanish/pftl-053-esp.pptx
py .\slides20.py -b pftl -s 055 -lang esp --ppt -output spanish/pftl-055-esp.pptx
py .\slides20.py -b pftl -s 059 -lang esp --ppt -output spanish/pftl-059-esp.pptx
py .\slides20.py -b pftl -s 067 -lang esp --ppt -output spanish/pftl-067-esp.pptx
py .\slides20.py -b pftl -s 068 -lang esp --ppt -output spanish/pftl-068-esp.pptx
py .\slides20.py -b pftl -s 070 -lang esp --ppt -output spanish/pftl-070-esp.pptx
py .\slides20.py -b pftl -s 071 -lang esp --ppt -output spanish/pftl-071-esp.pptx
py .\slides20.py -b pftl -s 076 -lang esp --ppt -output spanish/pftl-076-esp.pptx
py .\slides20.py -b pftl -s 080 -lang esp --ppt -output spanish/pftl-080-esp.pptx
py .\slides20.py -b pftl -s 085 -lang esp --ppt -output spanish/pftl-085-esp.pptx
py .\slides20.py -b pftl -s 086 -lang esp --ppt -output spanish/pftl-086-esp.pptx
py .\slides20.py -b pftl -s 090 -lang esp --ppt -output spanish/pftl-090-esp.pptx
py .\slides20.py -b pftl -s 093 -lang esp --ppt -output spanish/pftl-093-esp.pptx
py .\slides20.py -b pftl -s 111 -lang esp --ppt -output spanish/pftl-111-esp.pptx
py .\slides20.py -b pftl -s 115 -lang esp --ppt -output spanish/pftl-115-esp.pptx
py .\slides20.py -b pftl -s 120 -lang esp --ppt -output spanish/pftl-120-esp.pptx
py .\slides20.py -b pftl -s 124 -lang esp --ppt -output spanish/pftl-124-esp.pptx
py .\slides20.py -b pftl -s 125 -lang esp --ppt -output spanish/pftl-125-esp.pptx
py .\slides20.py -b pftl -s 131 -lang esp --ppt -output spanish/pftl-131-esp.pptx
py .\slides20.py -b pftl -s 136 -lang esp --ppt -output spanish/pftl-136-esp.pptx
py .\slides20.py -b pftl -s 137 -lang esp --ppt -output spanish/pftl-137-esp.pptx
py .\slides20.py -b pftl -s 160 -lang esp --ppt -output spanish/pftl-160-esp.pptx
py .\slides20.py -b pftl -s 163 -lang esp --ppt -output spanish/pftl-163-esp.pptx
py .\slides20.py -b pftl -s 179 -lang esp --ppt -output spanish/pftl-179-esp.pptx
py .\slides20.py -b pftl -s 184 -lang esp --ppt -output spanish/pftl-184-esp.pptx
py .\slides20.py -b pftl -s 189 -lang esp --ppt -output spanish/pftl-189-esp.pptx
py .\slides20.py -b pftl -s 190 -lang esp --ppt -output spanish/pftl-190-esp.pptx
py .\slides20.py -b pftl -s 191 -lang esp --ppt -output spanish/pftl-191-esp.pptx
py .\slides20.py -b pftl -s 193 -lang esp --ppt -output spanish/pftl-193-esp.pptx
py .\slides20.py -b pftl -s 197 -lang esp --ppt -output spanish/pftl-197-esp.pptx
py .\slides20.py -b pftl -s 200 -lang esp --ppt -output spanish/pftl-200-esp.pptx
py .\slides20.py -b pftl -s 203 -lang esp --ppt -output spanish/pftl-203-esp.pptx
py .\slides20.py -b pftl -s 207 -lang esp --ppt -output spanish/pftl-207-esp.pptx
py .\slides20.py -b pftl -s 208 -lang esp --ppt -output spanish/pftl-208-esp.pptx
py .\slides20.py -b pftl -s 217 -lang esp --ppt -output spanish/pftl-217-esp.pptx
py .\slides20.py -b pftl -s 226 -lang esp --ppt -output spanish/pftl-226-esp.pptx
py .\slides20.py -b pftl -s 237 -lang esp --ppt -output spanish/pftl-237-esp.pptx
py .\slides20.py -b pftl -s 238 -lang esp --ppt -output spanish/pftl-238-esp.pptx
py .\slides20.py -b pftl -s 248 -lang esp --ppt -output spanish/pftl-248-esp.pptx
py .\slides20.py -b pftl -s 250 -lang esp --ppt -output spanish/pftl-250-esp.pptx
py .\slides20.py -b pftl -s 253 -lang esp --ppt -output spanish/pftl-253-esp.pptx
py .\slides20.py -b pftl -s 255 -lang esp --ppt -output spanish/pftl-255-esp.pptx
py .\slides20.py -b pftl -s 261 -lang esp --ppt -output spanish/pftl-261-esp.pptx
py .\slides20.py -b pftl -s 262 -lang esp --ppt -output spanish/pftl-262-esp.pptx
py .\slides20.py -b pftl -s 263 -lang esp --ppt -output spanish/pftl-263-esp.pptx
py .\slides20.py -b pftl -s 268 -lang esp --ppt -output spanish/pftl-268-esp.pptx
py .\slides20.py -b pftl -s 272 -lang esp --ppt -output spanish/pftl-272-esp.pptx
py .\slides20.py -b pftl -s 282 -lang esp --ppt -output spanish/pftl-282-esp.pptx
py .\slides20.py -b pftl -s 288 -lang esp --ppt -output spanish/pftl-288-esp.pptx
py .\slides20.py -b pftl -s 291 -lang esp --ppt -output spanish/pftl-291-esp.pptx
py .\slides20.py -b pftl -s 297 -lang esp --ppt -output spanish/pftl-297-esp.pptx
py .\slides20.py -b pftl -s 299 -lang esp --ppt -output spanish/pftl-299-esp.pptx
py .\slides20.py -b pftl -s 322 -lang esp --ppt -output spanish/pftl-322-esp.pptx
py .\slides20.py -b pftl -s 327 -lang esp --ppt -output spanish/pftl-327-esp.pptx
py .\slides20.py -b pftl -s 336 -lang esp --ppt -output spanish/pftl-336-esp.pptx
py .\slides20.py -b pftl -s 345 -lang esp --ppt -output spanish/pftl-345-esp.pptx
py .\slides20.py -b pftl -s 356 -lang esp --ppt -output spanish/pftl-356-esp.pptx
py .\slides20.py -b pftl -s 359 -lang esp --ppt -output spanish/pftl-359-esp.pptx
py .\slides20.py -b pftl -s 362 -lang esp --ppt -output spanish/pftl-362-esp.pptx
py .\slides20.py -b pftl -s 368 -lang esp --ppt -output spanish/pftl-368-esp.pptx
py .\slides20.py -b pftl -s 369 -lang esp --ppt -output spanish/pftl-369-esp.pptx
py .\slides20.py -b pftl -s 379 -lang esp --ppt -output spanish/pftl-379-esp.pptx
py .\slides20.py -b pftl -s 380 -lang esp --ppt -output spanish/pftl-380-esp.pptx
py .\slides20.py -b pftl -s 384 -lang esp --ppt -output spanish/pftl-384-esp.pptx
py .\slides20.py -b pftl -s 387 -lang esp --ppt -output spanish/pftl-387-esp.pptx
py .\slides20.py -b pftl -s 388 -lang esp --ppt -output spanish/pftl-388-esp.pptx
py .\slides20.py -b pftl -s 389 -lang esp --ppt -output spanish/pftl-389-esp.pptx
py .\slides20.py -b pftl -s 392 -lang esp --ppt -output spanish/pftl-392-esp.pptx
py .\slides20.py -b pftl -s 394 -lang esp --ppt -output spanish/pftl-394-esp.pptx
py .\slides20.py -b pftl -s 397 -lang esp --ppt -output spanish/pftl-397-esp.pptx
py .\slides20.py -b pftl -s 402 -lang esp --ppt -output spanish/pftl-402-esp.pptx
py .\slides20.py -b pftl -s 408 -lang esp --ppt -output spanish/pftl-408-esp.pptx
py .\slides20.py -b pftl -s 412 -lang esp --ppt -output spanish/pftl-412-esp.pptx
py .\slides20.py -b pftl -s 415 -lang esp --ppt -output spanish/pftl-415-esp.pptx
py .\slides20.py -b pftl -s 416 -lang esp --ppt -output spanish/pftl-416-esp.pptx
py .\slides20.py -b pftl -s 419 -lang esp --ppt -output spanish/pftl-419-esp.pptx
py .\slides20.py -b pftl -s 421 -lang esp --ppt -output spanish/pftl-421-esp.pptx
py .\slides20.py -b pftl -s 425 -lang esp --ppt -output spanish/pftl-425-esp.pptx
py .\slides20.py -b pftl -s 434 -lang esp --ppt -output spanish/pftl-434-esp.pptx
py .\slides20.py -b pftl -s 436 -lang esp --ppt -output spanish/pftl-436-esp.pptx
py .\slides20.py -b pftl -s 438 -lang esp --ppt -output spanish/pftl-438-esp.pptx
py .\slides20.py -b pftl -s 440 -lang esp --ppt -output spanish/pftl-440-esp.pptx
py .\slides20.py -b pftl -s 442 -lang esp --ppt -output spanish/pftl-442-esp.pptx
py .\slides20.py -b pftl -s 447 -lang esp --ppt -output spanish/pftl-447-esp.pptx
py .\slides20.py -b pftl -s 450 -lang esp --ppt -output spanish/pftl-450-esp.pptx
py .\slides20.py -b pftl -s 452 -lang esp --ppt -output spanish/pftl-452-esp.pptx
py .\slides20.py -b pftl -s 454 -lang esp --ppt -output spanish/pftl-454-esp.pptx
py .\slides20.py -b pftl -s 456 -lang esp --ppt -output spanish/pftl-456-esp.pptx
py .\slides20.py -b pftl -s 462 -lang esp --ppt -output spanish/pftl-462-esp.pptx
py .\slides20.py -b pftl -s 463 -lang esp --ppt -output spanish/pftl-463-esp.pptx
py .\slides20.py -b pftl -s 492 -lang esp --ppt -output spanish/pftl-492-esp.pptx
py .\slides20.py -b pftl -s 495 -lang esp --ppt -output spanish/pftl-495-esp.pptx
py .\slides20.py -b pftl -s 499 -lang esp --ppt -output spanish/pftl-499-esp.pptx
py .\slides20.py -b pftl -s 500 -lang esp --ppt -output spanish/pftl-500-esp.pptx
py .\slides20.py -b pftl -s 501 -lang esp --ppt -output spanish/pftl-501-esp.pptx
py .\slides20.py -b pftl -s 509 -lang esp --ppt -output spanish/pftl-509-esp.pptx
py .\slides20.py -b pftl -s 510 -lang esp --ppt -output spanish/pftl-510-esp.pptx
py .\slides20.py -b pftl -s 511 -lang esp --ppt -output spanish/pftl-511-esp.pptx
py .\slides20.py -b pftl -s 515 -lang esp --ppt -output spanish/pftl-515-esp.pptx
py .\slides20.py -b pftl -s 519 -lang esp --ppt -output spanish/pftl-519-esp.pptx
py .\slides20.py -b pftl -s 520 -lang esp --ppt -output spanish/pftl-520-esp.pptx
py .\slides20.py -b pftl -s 523 -lang esp --ppt -output spanish/pftl-523-esp.pptx
py .\slides20.py -b pftl -s 528 -lang esp --ppt -output spanish/pftl-528-esp.pptx
py .\slides20.py -b pftl -s 529 -lang esp --ppt -output spanish/pftl-529-esp.pptx
py .\slides20.py -b pftl -s 532 -lang esp --ppt -output spanish/pftl-532-esp.pptx
py .\slides20.py -b pftl -s 538 -lang esp --ppt -output spanish/pftl-538-esp.pptx
py .\slides20.py -b pftl -s 541 -lang esp --ppt -output spanish/pftl-541-esp.pptx
py .\slides20.py -b pftl -s 544 -lang esp --ppt -output spanish/pftl-544-esp.pptx
py .\slides20.py -b pftl -s 557 -lang esp --ppt -output spanish/pftl-557-esp.pptx
py .\slides20.py -b pftl -s 564 -lang esp --ppt -output spanish/pftl-564-esp.pptx
py .\slides20.py -b pftl -s 565 -lang esp --ppt -output spanish/pftl-565-esp.pptx
py .\slides20.py -b pftl -s 581 -lang esp --ppt -output spanish/pftl-581-esp.pptx
py .\slides20.py -b pftl -s 583 -lang esp --ppt -output spanish/pftl-583-esp.pptx
py .\slides20.py -b pftl -s 587 -lang esp --ppt -output spanish/pftl-587-esp.pptx
py .\slides20.py -b pftl -s 588 -lang esp --ppt -output spanish/pftl-588-esp.pptx
py .\slides20.py -b pftl -s 593 -lang esp --ppt -output spanish/pftl-593-esp.pptx
py .\slides20.py -b pftl -s 595 -lang esp --ppt -output spanish/pftl-595-esp.pptx
py .\slides20.py -b pftl -s 598 -lang esp --ppt -output spanish/pftl-598-esp.pptx
py .\slides20.py -b pftl -s 599 -lang esp --ppt -output spanish/pftl-599-esp.pptx
py .\slides20.py -b pftl -s 612 -lang esp --ppt -output spanish/pftl-612-esp.pptx
py .\slides20.py -b pftl -s 613 -lang esp --ppt -output spanish/pftl-613-esp.pptx
py .\slides20.py -b pftl -s 618 -lang esp --ppt -output spanish/pftl-618-esp.pptx
py .\slides20.py -b pftl -s 620 -lang esp --ppt -output spanish/pftl-620-esp.pptx
py .\slides20.py -b pftl -s 621 -lang esp --ppt -output spanish/pftl-621-esp.pptx
py .\slides20.py -b pftl -s 622 -lang esp --ppt -output spanish/pftl-622-esp.pptx
py .\slides20.py -b pftl -s 624 -lang esp --ppt -output spanish/pftl-624-esp.pptx
py .\slides20.py -b pftl -s 634 -lang esp --ppt -output spanish/pftl-634-esp.pptx
py .\slides20.py -b pftl -s 640 -lang esp --ppt -output spanish/pftl-640-esp.pptx
py .\slides20.py -b pftl -s 642 -lang esp --ppt -output spanish/pftl-642-esp.pptx
py .\slides20.py -b pftl -s 653 -lang esp --ppt -output spanish/pftl-653-esp.pptx
py .\slides20.py -b pftl -s 655 -lang esp --ppt -output spanish/pftl-655-esp.pptx
py .\slides20.py -b pftl -s 656 -lang esp --ppt -output spanish/pftl-656-esp.pptx
py .\slides20.py -b pftl -s 660 -lang esp --ppt -output spanish/pftl-660-esp.pptx
py .\slides20.py -b pftl -s 662 -lang esp --ppt -output spanish/pftl-662-esp.pptx
py .\slides20.py -b pftl -s 667 -lang esp --ppt -output spanish/pftl-667-esp.pptx
py .\slides20.py -b pftl -s 669 -lang esp --ppt -output spanish/pftl-669-esp.pptx
py .\slides20.py -b pftl -s 671 -lang esp --ppt -output spanish/pftl-671-esp.pptx
py .\slides20.py -b pftl -s 682 -lang esp --ppt -output spanish/pftl-682-esp.pptx
py .\slides20.py -b pftl -s 685 -lang esp --ppt -output spanish/pftl-685-esp.pptx
py .\slides20.py -b pftl -s 687 -lang esp --ppt -output spanish/pftl-687-esp.pptx
py .\slides20.py -b pftl -s 688 -lang esp --ppt -output spanish/pftl-688-esp.pptx
py .\slides20.py -b pftl -s 707 -lang esp --ppt -output spanish/pftl-707-esp.pptx
py .\slides20.py -b pftl -s 711 -lang esp --ppt -output spanish/pftl-711-esp.pptx
py .\slides20.py -b pftl -s 714 -lang esp --ppt -output spanish/pftl-714-esp.pptx
py .\slides20.py -b pftl -s 717 -lang esp --ppt -output spanish/pftl-717-esp.pptx
py .\slides20.py -b pftl -s 726 -lang esp --ppt -output spanish/pftl-726-esp.pptx
py .\slides20.py -b pftl -s 732 -lang esp --ppt -output spanish/pftl-732-esp.pptx
py .\slides20.py -b pftl -s 738 -lang esp --ppt -output spanish/pftl-738-esp.pptx
py .\slides20.py -b pftl -s 739 -lang esp --ppt -output spanish/pftl-739-esp.pptx
py .\slides20.py -b pftl -s 742 -lang esp --ppt -output spanish/pftl-742-esp.pptx
py .\slides20.py -b pftl -s 752 -lang esp --ppt -output spanish/pftl-752-esp.pptx
py .\slides20.py -b pftl -s 756 -lang esp --ppt -output spanish/pftl-756-esp.pptx
py .\slides20.py -b pftl -s 758 -lang esp --ppt -output spanish/pftl-758-esp.pptx
py .\slides20.py -b pftl -s 761 -lang esp --ppt -output spanish/pftl-761-esp.pptx
py .\slides20.py -b pftl -s 764 -lang esp --ppt -output spanish/pftl-764-esp.pptx
py .\slides20.py -b pftl -s 766 -lang esp --ppt -output spanish/pftl-766-esp.pptx
py .\slides20.py -b pftl -s 776 -lang esp --ppt -output spanish/pftl-776-esp.pptx
py .\slides20.py -b pftl -s 782 -lang esp --ppt -output spanish/pftl-782-esp.pptx
py .\slides20.py -b pftl -s 784 -lang esp --ppt -output spanish/pftl-784-esp.pptx
py .\slides20.py -b pftl -s 787 -lang esp --ppt -output spanish/pftl-787-esp.pptx
py .\slides20.py -b pftl -s 798 -lang esp --ppt -output spanish/pftl-798-esp.pptx
py .\slides20.py -b pftl -s 800 -lang esp --ppt -output spanish/pftl-800-esp.pptx
py .\slides20.py -b pftl -s 810 -lang esp --ppt -output spanish/pftl-810-esp.pptx
py .\slides20.py -b pftl -s 826 -lang esp --ppt -output spanish/pftl-826-esp.pptx
py .\slides20.py -b pftl -s 839 -lang esp --ppt -output spanish/pftl-839-esp.pptx
py .\slides20.py -b pftl -s 868 -lang esp --ppt -output spanish/pftl-868-esp.pptx
py .\slides20.py -b pftl -s 871 -lang esp --ppt -output spanish/pftl-871-esp.pptx
py .\slides20.py -b pftl -s 884 -lang esp --ppt -output spanish/pftl-884-esp.pptx
py .\slides20.py -b pftl -s 929 -lang esp --ppt -output spanish/pftl-929-esp.pptx
py .\slides20.py -b pftl -s 941 -lang esp --ppt -output spanish/pftl-941-esp.pptx
py .\slides20.py -b pftl -s 945 -lang esp --ppt -output spanish/pftl-945-esp.pptx
py .\slides20.py -b pftl -s 950 -lang esp --ppt -output spanish/pftl-950-esp.pptx
py .\slides20.py -b pftl -s 975 -lang esp --ppt -output spanish/pftl-975-esp.pptx
py .\slides20.py -b pftl -s 989 -lang esp --ppt -output spanish/pftl-989-esp.pptx
py .\slides20.py -b phss -s 010 -lang esp --ppt -output spanish/phss-010-esp.pptx
py .\slides20.py -b phss -s 029 -lang esp --ppt -output spanish/phss-029-esp.pptx
py .\slides20.py -b phss -s 088 -lang esp --ppt -output spanish/phss-088-esp.pptx
py .\slides20.py -b phss -s 091 -lang esp --ppt -output spanish/phss-091-esp.pptx
py .\slides20.py -b phss -s 105 -lang esp --ppt -output spanish/phss-105-esp.pptx
py .\slides20.py -b phss -s 111 -lang esp --ppt -output spanish/phss-111-esp.pptx
py .\slides20.py -b phss -s 157 -lang esp --ppt -output spanish/phss-157-esp.pptx
py .\slides20.py -b phss -s 198 -lang esp --ppt -output spanish/phss-198-esp.pptx
py .\slides20.py -b phss -s 199 -lang esp --ppt -output spanish/phss-199-esp.pptx
py .\slides20.py -b phss -s 223 -lang esp --ppt -output spanish/phss-223-esp.pptx
py .\slides20.py -b phss -s 229 -lang esp --ppt -output spanish/phss-229-esp.pptx
py .\slides20.py -b phss -s 231 -lang esp --ppt -output spanish/phss-231-esp.pptx
py .\slides20.py -b phss -s 275 -lang esp --ppt -output spanish/phss-275-esp.pptx
py .\slides20.py -b phss -s 277 -lang esp --ppt -output spanish/phss-277-esp.pptx
py .\slides20.py -b phss -s 297 -lang esp --ppt -output spanish/phss-297-esp.pptx
py .\slides20.py -b phss -s 306 -lang esp --ppt -output spanish/phss-306-esp.pptx
py .\slides20.py -b phss -s 341 -lang esp --ppt -output spanish/phss-341-esp.pptx
py .\slides20.py -b phss -s 357 -lang esp --ppt -output spanish/phss-357-esp.pptx
py .\slides20.py -b phss -s 448 -lang esp --ppt -output spanish/phss-448-esp.pptx
py .\slides20.py -b phss -s 451 -lang esp --ppt -output spanish/phss-451-esp.pptx
py .\slides20.py -b phss -s 531 -lang esp --ppt -output spanish/phss-531-esp.pptx
py .\slides20.py -b phss -s 591 -lang esp --ppt -output spanish/phss-591-esp.pptx
py .\slides20.py -b phss -s 650 -lang esp --ppt -output spanish/phss-650-esp.pptx
py .\slides20.py -b phss -s 699 -lang esp --ppt -output spanish/phss-699-esp.pptx
py .\slides20.py -b eh -s 101 -lang esp --ppt -output spanish/eh-101-esp.pptx
py .\slides20.py -b eh -s 102 -lang esp --ppt -output spanish/eh-102-esp.pptx
py .\slides20.py -b eh -s 103 -lang esp --ppt -output spanish/eh-103-esp.pptx
py .\slides20.py -b eh -s 104 -lang esp --ppt -output spanish/eh-104-esp.pptx
py .\slides20.py -b eh -s 105 -lang esp --ppt -output spanish/eh-105-esp.pptx

